project_id = "ggzdhmltktbcpuwgvljn"

[functions.system-audit]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = false

[functions.check-connect-status]
verify_jwt = false

[functions.create-connect-login-link]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.list-stripe-payments]
verify_jwt = false

[functions.neural-brain]
verify_jwt = false

[functions.api-consumer-agent]
verify_jwt = false

[functions.payment-bot]
verify_jwt = false

[functions.volume-generator]
verify_jwt = false

[functions.api-marketplace]
verify_jwt = false
